"""End-to-end proof: every testbed file fires exactly its manifest rules.

The corpus lives in testbed/ (one vulnerable file per rule, generated by
scripts/generate_testbed.py); testbed/manifest.json records the per-file
expectation. This runs inside the existing tests.yml workflow - no separate
CI job needed.
"""

import json
from pathlib import Path

import pytest

from megasast.engine import scan_file
from megasast.parser import TreeSitterParser
from megasast.rules.registry import RULES

TESTBED = Path(__file__).resolve().parent.parent / "testbed"
MANIFEST = json.loads((TESTBED / "manifest.json").read_text(encoding="utf-8"))


def _entry_id(entry):
    return entry["file"]


def test_testbed_manifest_covers_all_registered_rules():
    covered = {rule for entry in MANIFEST for rule in entry["expected_rules"]}
    registered = {rule.id for rule in RULES}
    assert registered <= covered, f"rules missing from testbed: {sorted(registered - covered)}"


@pytest.mark.parametrize("entry", MANIFEST, ids=_entry_id)
def test_testbed_file_fires_expected_rules(entry):
    path = TESTBED / entry["file"]
    assert path.is_file(), f"testbed file missing: {path}"
    expected = set(entry["expected_rules"])

    findings = scan_file(path, TreeSitterParser(), allowed_rules=expected)

    assert {f.rule_id for f in findings} == expected, (
        f"{entry['file']}: got {[f.rule_id for f in findings]}, want {sorted(expected)}"
    )
    assert len(findings) == len(expected), (
        f"{entry['file']}: expected {len(expected)} finding(s), got {len(findings)}"
    )
